typography_spectrum: 0.9021922
color:
  brandStrength: 0.4200695
  lightness: 0.2639123
  saturation: 0.9772344
  rhythmicContrast: 0.7057335
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
github: true
opengraph:
  type: 'https://www.facebook.com/Lifein3Courses/photos'
layout_spectrum: 0.4671578
logo: null
name: Life In 3 Courses
navigation:
  - name: Health and Wellness
    id: 65d2a26f-0f6a-4fd4-a874-96333cb9e765
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Life In 3 Courses
content: []
description: Enjoying the journey of life after 50
