layout_spectrum: 0.5532574549515612
typography_spectrum: 0.9477803611321983
color:
  brandStrength: 0.45016506490214625
  lightness: 0.5234288531561189
  saturation: 0.1648665110469049
  rhythmicContrast: 0.08781473487910658
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
opengraph:
  type: 'https://www.facebook.com/Lifein3Courses/photos'
logo: null
name: Life In 3 Courses
navigation:
  - name: Health and Wellness
    id: 65d2a26f-0f6a-4fd4-a874-96333cb9e765
    type: content
  - name: Lifestyle
    id: 4976aa0a-6ac7-4c4e-a048-c0012671462b
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Life In 3 Courses
content: []
description: Enjoying the journey of life after 50
