content: []
description: Enjoying the journey of life after 50
title: Life In 3 Courses
github: true
layout_spectrum: 0.8114035
name: Life In 3 Courses
opengraph:
  type: 'https://www.facebook.com/Lifein3Courses/photos'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4200695
  lightness: 0.01691729
  saturation: 0.2255639
  rhythmicContrast: 0.2725564
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.9021922
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b786bf57-071d-4a39-b06d-4dd9c975570a.jpg
